### ISSUE TITLE
 TypeError: cb is not a function

### ISSUE THREAD

**Issue by onyx-nxt** [rubenstolk/printscreen.js#2]
I keep getting this: ```js

TypeError: cb is not a function
    at /root/COOL-BOI-BOT/node_modules/printscreen/lib/index.js:38:57
    at /root/COOL-BOI-BOT/node_modules/node-phantom-simple/node-phantom-simple.js:281:7
    at ChildProcess.immediateExit (/root/COOL-BOI-BOT/node_modules/node-phantom-simple/node-phantom-simple.js:153:14)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
``` how 2 fix?

**Comment by onyx-nxt** [comment]
I fixed it ignore this
